### ISSUE TITLE
Function `class_uses` does not return traits used on parent class

### ISSUE THREAD

**Issue by ben221199** [laravel-json-api/boolean-softdeletes#1]
In my project all models are soft-deletable, so soft-deletion (and some other common properties) are defined in a parent Model called `ObjectModel`. This model has the `SoftDeletesBoolean` trait. However, this trait is not detected in `SoftDeleteBooleanDriver` because it is using `class_uses`, that only returns traits in the current class and not in parent classes.

**Comment by ben221199** [comment]
I see I didn't use this package yet. That is because there is no release yet.

**Comment by ben221199** [comment]
Okay, I moved to this package having `use SoftDeletesBoolean;` on the schemas. Now it prints: `Expecting a model that is boolean soft-deletable.` instead of `Expecting a model that is soft-deletable.`, so the issue is still there.

**Comment by ben221199** [comment]
It works when using #2 in combination with moving to `SoftDeletesBoolean` in the schemas.

**Comment by ben221199** [comment]
Issue could be closed when PR is merged and there is a release on Packagist.

**Comment by lindyhopchris** [comment]
Thanks for the PR - have merged it.

I haven't tagged a version of this repo yet because I'm waiting on one PR to be merged in the boolean soft-deletes package, and for them to then tag it.
