### ISSUE TITLE
Laravel 10 Support

### ISSUE THREAD

**Issue by tribecar-shurn** [laravel-json-api/boolean-softdeletes#4]
It's conflicting with other installs, like laravel-json-api/hashids ^2

**Comment by lindyhopchris** [comment]
Unfortunately we cannot upgrade until `tenantcloud/laravel-boolean-softdeletes` upgrades to Laravel 10.

**Comment by ben221199** [comment]
Updated @lindyhopchris.

**Comment by lindyhopchris** [comment]
Yep I saw the tag go through. I'm unlikely to get to this tonight, but should be able to update tomorrow evening (UK time).

**Comment by lindyhopchris** [comment]
Got home earlier than expected so just had time to sort this out. `v2.0.0` tagged!
